version: "3.9"
services:

    organizr:
        image: organizr/organizr:latest
        container_name: organizr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/organizr:/config
        ports:
            - 9983:80
        restart: always
        networks:
            - private 

    sonarr:
        image: linuxserver/sonarr:develop #ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/sonarr:/config
            - ${media}/download:/downloads
            - ${media}/series:/tv
        ports:
            - 8989:8989
        restart: always
        networks:
            - private

    radarr:
        image: ghcr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/radarr:/config
            - ${app_data}/radarr/backup:/tmp #directory for backups
            - ${media}/download:/downloads
            - ${media}/moviez:/movies
        ports:
            - 7878:7878
        restart: always
        networks:
            - private

    lidarr:
        image: ghcr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/lidarr:/config
            - ${media}/download:/downloads
            - ${media}/music:/music
        ports:
            - 8686:8686
        restart: always
        networks:
            - private

    Bazarr:
        image: ghcr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/bazaarr:/config
            - ${media}/moviez:/movies
            - ${media}/series:/tv
        ports:
            - 6767:6767
        restart: always
        networks:
            - private

    jackett:
        image: linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/jackett:/config
            - ${media}/download:/downloads
        ports:
            - 9117:9117
        restart: always
        networks:
            - private
    
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/prowlarr:/config
        restart: always
        network_mode: host #9696

    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - LOG_LEVEL=debug
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        ports:
            - 5055:5055
        volumes:
            - ${app_data}/overseer:/app/config
        restart: always
        networks:
            - private
        dns:
            - 8.8.8.8
            - 1.1.1.1

networks:
    private:
        external: true
