services:

    organizr:
        image: ghcr.io/organizr/organizr
        container_name: organizr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/organizr:/config
        ports:
            - 9983:80
        restart: always
        networks:
            - private

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/sonarr:/config
            - ${media}/download:/downloads
            - ${media}/series:/tv
        ports:
            - 8989:8989
        restart: always
        networks:
            - private

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/radarr:/config
            - ${app_data}/radarr/backup:/tmp #directory for backups
            - ${media}/download:/downloads
            - ${media}/moviez:/movies
        ports:
            - 7878:7878
        restart: always
        networks:
            - private

    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/lidarr:/config
            - ${media}/download:/downloads
            - ${media}/music:/music
        ports:
            - 8686:8686
        restart: always
        networks:
            - private

    Bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/bazaarr:/config
            - ${media}/moviez:/movies
            - ${media}/series:/tv
        ports:
            - 6767:6767
        restart: always
        networks:
            - private

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/prowlarr:/config
        ports:
            - 9696:9696
        restart: always
        networks:
            - private

    overseerr:
        image: ghcr.io/seerr-team/seerr:latest
        init: true
        container_name: seerr
        environment:
            - LOG_LEVEL=debug
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        ports:
            - 5055:5055
        volumes:
            - ${app_data}/overseer:/app/config
        restart: always
        healthcheck:
            test: wget --no-verbose --tries=1 --spider
                http://localhost:5055/api/v1/settings/public || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        networks:
            - private
        dns:
            - 8.8.8.8
            - 1.1.1.1

    watchlistarr:
        image: nylonee/watchlistarr:latest
        container_name: watchlistarr
        environment:
            - SONARR_BASE_URL=$sonarr_url
            - SONARR_API_KEY=$sonarr_api
            - RADARR_BASE_URL=$radarr_url
            - RADARR_API_KEY=$radarr_api
            - PLEX_TOKEN=$plex_token
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        restart: always
        volumes:
            - ${app_data}/watchlistarr:/app/config

    torrserver:
        image: ghcr.io/yourok/torrserver:latest
        container_name: torrserver
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
            - TS_DONTKILL=1
            - TS_HTTPAUTH=0
            - TS_CONF_PATH=/opt/ts/config
            - TS_TORR_DIR=/opt/ts/torrents
        volumes:
            - ${app_data}/torrserver/CACHE:/opt/ts/torrents
            - ${app_data}/torrserver/CONFIG:/opt/ts/config
        restart: unless-stopped
        network_mode: "host"

networks:
    private:
        external: true
